export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_PRODUCTS_FROM_CART = "GET_PRODUCTS_FROM_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const ADD_PRODUCT_TO_PAYED = "ADD_PRODUCT_TO_PAYED";
